import { Providers } from '@/components/Providers/providers'
import type { Metadata } from 'next'
import { ToastContainer } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css'
// These styles apply to every route in the application
import '../styles/globals.css'

export const metadata: Metadata = {
    title: 'Events Registration App',
    description: 'Generated by nickbron',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body>
                <Providers>
                    {children}
                    <ToastContainer position="top-center" autoClose={2000} limit={1} />
                </Providers>
            </body>
        </html>
    )
}
