import NavBar from '@/components/NavBar/NavBar'
import { Providers } from '@/components/Providers/providers'
import { ThemeProvider } from '@/components/Providers/theme-provider'
import { Inter as FontSans } from 'next/font/google'
import { cn } from '@/lib/utils'
import type { Metadata } from 'next'
import { ToastContainer } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css'
// These styles apply to every route in the application
import '../styles/globals.css'

export const metadata: Metadata = {
    title: 'Events Registration App',
    description: 'Generated by nickbron',
}

const fontSans = FontSans({
    subsets: ['latin'],
    variable: '--font-sans',
})

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <Providers>
                <body className={cn('min-w-screen bg-background font-sans antialiased', fontSans.variable)}>
                    <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
                        <NavBar />
                        {children}
                        <ToastContainer position="top-center" autoClose={2000} limit={1} />
                    </ThemeProvider>
                </body>
            </Providers>
        </html>
    )
}
